# Generated by Django 6.0.8 on 2026-09-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("local", models.CharField(max_length=200)),
                ("categoria", models.CharField(max_length=100)),
                ("informacoes_adicionais", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
