# Generated by Django 6.0.8 on 2026-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventosif", "0002_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mensagem", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
